In [2]:
import pandas as pd 
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, f1_score
from sklearn.model_selection import GridSearchCV

from hyperopt import hp
from hyperopt import fmin, tpe, space_eval
from hyperopt import hp, fmin, tpe, rand, pyll, STATUS_OK, STATUS_FAIL, Trials, space_eval
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import sys
sys.path.append("../../src")
from my_functions import *
from preprocessing_data_model import format_data_origin 
from modeling_and_erros import *




2022-04-30 16:18:27.219344: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-30 16:18:27.219410: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[nltk_data] Downloading package omw-1.4 to /home/enrique/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [36]:
col_text = "tweet"
path_train = "../../data/raw/training.csv"
path_test = "../../test/development_test.csv"

path_evaluate = "../../data/evaluate/test_without_labels.csv"
train_test = format_data_origin(path_train, path_test, path_evaluate)
print(train_test["train"].shape)
print(train_test["test"].shape)

train
test
evaluate
(314, 6)
(20, 6)


In [52]:
X_train, X_test, y_train, y_test =train_test_split(train_test["train"].loc[:,[ "tweet"]], train_test["train"].loc[:,var_predictions], 
                                                    random_state=19970808, test_size=0.2)

In [53]:
X_train_t, X_test = selection_representation(X_train["tweet"].tolist().copy(), X_test["tweet"].tolist().copy(), "TFIDF")



In [54]:
X_train, X_evaluate = selection_representation(X_train["tweet"].tolist(), train_test["evaluate"]["tweet"].tolist(), "TFIDF")


In [65]:
param_grid_reg = [
    {"C": np.logspace(-3, 3, 20),
     "penalty": ["l1", "l2"]
     }
    ]

In [66]:
y_predict_evaluate = {}
for label in var_predictions:
    model = LogisticRegression(max_iter=3000, n_jobs=-1)
    model = GridSearchCV(model, param_grid=param_grid_reg, cv=10, verbose=True, n_jobs=-1)
    model.fit(X_train, y_train[label])
    print(model.score(X_train, y_train[label]))
    print(confusion_matrix(model.predict(X_train), y_train[label]))
    print(model.score(X_test, y_test[label]))
    print(confusion_matrix(model.predict(X_test), y_test[label]))

    y_predict_evaluate[label] = model.predict(X_evaluate)



Fitting 10 folds for each of 40 candidates, totalling 400 fits


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sk

0.9960159362549801
[[104   0]
 [  1 146]]
0.6984126984126984
[[18  5]
 [14 26]]
Fitting 10 folds for each of 40 candidates, totalling 400 fits


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sk

0.9960159362549801
[[ 51   0]
 [  1 199]]
0.9365079365079365
[[ 8  2]
 [ 2 51]]
Fitting 10 folds for each of 40 candidates, totalling 400 fits


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sk

1.0
[[140   0]
 [  0 111]]
0.9206349206349206
[[33  0]
 [ 5 25]]
Fitting 10 folds for each of 40 candidates, totalling 400 fits


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/sk

1.0
[[60  0  0  0]
 [ 0 80  0  0]
 [ 0  0 76  0]
 [ 0  0  0 35]]
0.8571428571428571
[[14  1  0  2]
 [ 0 18  0  0]
 [ 1  3 18  1]
 [ 1  0  0  4]]


In [67]:
result = pd.DataFrame(y_predict_evaluate)
result["label"] = train_test["evaluate"]["label"]
result["match"] = result[["ideology_binary","ideology_multiclass"]].apply(lambda x: len(re.findall(x[0],x[1])),axis=1)
sum(result["match"]==0)
# result[["label"]+var_predictions].to_csv("../../data/evaluate/results_2.csv", index=False)

4

In [58]:
result_baseline = pd.read_csv("../../data/evaluate/results.csv")
result_baseline["match"] = result_baseline[["ideology_binary","ideology_multiclass"]].apply(lambda x: len(re.findall(x[0],x[1])),axis=1)
sum(result_baseline["match"]==0)

5

In [59]:
for i in var_predictions:
    print(confusion_matrix(result_baseline[i], result[i]))

[[32  3]
 [ 7 63]]
[[18  0]
 [ 2 85]]
[[59  4]
 [ 0 42]]
[[27  1  0  0]
 [ 1 32  1  0]
 [ 0  0 28  0]
 [ 0  0  0 15]]


In [60]:
result[result.match==0]

gender  profession ideology_binary ideology_multiclass     label  match
42     male  politician            left               right  @user254      0
84   female  journalist           right                left  @user446      0
95     male  politician           right       moderate_left   @user50      0
104    male  politician           right                left   @user79      0

In [61]:
pd.merge(result, result_baseline, on=["label"])

gender_x profession_x ideology_binary_x ideology_multiclass_x     label  \
0     female   politician              left         moderate_left  @user101   
1       male   politician             right        moderate_right  @user103   
2       male   politician              left                  left  @user104   
3     female   politician             right                 right   @user11   
4     female   journalist              left                  left  @user115   
..       ...          ...               ...                   ...       ...   
100     male   journalist              left                  left   @user63   
101     male   journalist              left                  left   @user64   
102     male   journalist              left                  left   @user65   
103     male   politician              left                  left   @user67   
104     male   politician             right                  left   @user79   

     match_x gender_y profession_y ideology_binary_y ideology_multiclass_y  \
0          1   female   politician              left         moderate_left   
1          1     male   politician             right        moderate_right   
2          1     male   politician              left                  left   
3          1   female   politician             right                 right   
4          1   female   journalist              left                  left   
..       ...      ...          ...               ...                   ...   
100        1     male   journalist              left                  left   
101        1     male   politician              left                  left   
102        1     male   journalist              left                  left   
103        1     male   politician              left                  left   
104        0     male   politician             right                  left   

     match_y  
0          1  
1          1  
2          1  
3          1  
4          1  
..       ...  
100        1  
101        1  
102        1  
103        1  
104        0  

[105 rows x 11 columns]

In [62]:
pd.merge(result, result_baseline, on=["label"])

gender_x profession_x ideology_binary_x ideology_multiclass_x     label  \
0     female   politician              left         moderate_left  @user101   
1       male   politician             right        moderate_right  @user103   
2       male   politician              left                  left  @user104   
3     female   politician             right                 right   @user11   
4     female   journalist              left                  left  @user115   
..       ...          ...               ...                   ...       ...   
100     male   journalist              left                  left   @user63   
101     male   journalist              left                  left   @user64   
102     male   journalist              left                  left   @user65   
103     male   politician              left                  left   @user67   
104     male   politician             right                  left   @user79   

     match_x gender_y profession_y ideology_binary_y ideology_multiclass_y  \
0          1   female   politician              left         moderate_left   
1          1     male   politician             right        moderate_right   
2          1     male   politician              left                  left   
3          1   female   politician             right                 right   
4          1   female   journalist              left                  left   
..       ...      ...          ...               ...                   ...   
100        1     male   journalist              left                  left   
101        1     male   politician              left                  left   
102        1     male   journalist              left                  left   
103        1     male   politician              left                  left   
104        0     male   politician             right                  left   

     match_y  
0          1  
1          1  
2          1  
3          1  
4          1  
..       ...  
100        1  
101        1  
102        1  
103        1  
104        0  

[105 rows x 11 columns]

### Xgboots

In [68]:
from xgboost import XGBClassifier as XGBoostClassifier

param_grid_xgboots =  {
 'max_depth':range(3,10,2),
 'min_child_weight':range(1,6,2)
}

In [84]:
label

'gender'

In [88]:
y_train

gender  profession ideology_binary ideology_multiclass
33   female  politician            left                left
238    male  politician            left       moderate_left
228  female  politician            left       moderate_left
103    male  politician            left       moderate_left
70   female  politician            left       moderate_left
..      ...         ...             ...                 ...
41     male  politician           right               right
256  female  politician            left                left
199  female  politician            left       moderate_left
15     male  journalist           right               right
81     male  journalist           right               right

[251 rows x 4 columns]

In [89]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [90]:
y_predict_evaluate = {}
for label in var_predictions:
    if label in ['gender', 'profession', 'ideology_binary']:
        model = XGBoostClassifier(seed=19970808, use_label_encoder=True, objective="binary:logistic")
    else:
        model = XGBoostClassifier(seed=19970808, use_label_encoder=True, objective="multi:softprob")
    model = GridSearchCV(model, param_grid=param_grid_xgboots, cv=3, verbose=False, n_jobs=10)
    model.fit(X_train, y_train[label])
    print(model.score(X_train, y_train[label]))
    print(confusion_matrix(model.predict(X_train), y_train[label]))
    print(model.score(X_test,y_test[label]))
    print(confusion_matrix(model.predict(X_test), y_test[label]))

    y_predict_evaluate[label] = model.predict(X_evaluate)

/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

[16:57:26] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
1.0
[[105   0]
 [  0 146]]
0.7777777777777778
[[22  4]
 [10 27]]


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

[16:58:26] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0.9960159362549801
[[ 52   1]
 [  0 198]]
0.8571428571428571
[[ 4  3]
 [ 6 50]]


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

[16:59:35] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
1.0
[[140   0]
 [  0 111]]
0.9047619047619048
[[34  2]
 [ 4 23]]


/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home/enrique/anaconda3/envs/automl/lib/python3.9/

[17:02:26] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
1.0
[[60  0  0  0]
 [ 0 80  0  0]
 [ 0  0 76  0]
 [ 0  0  0 35]]
0.7619047619047619
[[12  2  0  1]
 [ 3 17  2  0]
 [ 0  3 16  3]
 [ 1  0  0  3]]
[16:48:53] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:25] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metr

[16:48:53] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:25] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:50:12] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

[16:48:52] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:25] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:49] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:50:11] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

[16:48:53] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:27] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:52] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:50:15] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

[16:48:53] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:26] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:49:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:50:13] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

In [74]:
model = XGBoostClassifier(seed=19970808, use_label_encoder=True)
# model = GridSearchCV(model, param_grid=param_grid_xgboots, cv=3, verbose=True, n_jobs=10)
model.fit(X_train, y_train["gender"])

[16:41:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=19970808,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=19970808,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [79]:
confusion_matrix(model.predict(X_train), y_train["gender"])

array([[105,   0],
       [  0, 146]])

In [78]:
confusion_matrix(model.predict(X_test), y_test["gender"])

array([[19,  5],
       [13, 26]])

In [75]:
print("Training...")
error_all = train_model_with_accuracy(X_train, X_test, train_test["train"][["label"]+var_predictions].copy(), 
        train_test["test"][["label"]+var_predictions].copy(), "LogisticRegression")


Training...
2


ValueError: Found input variables with inconsistent numbers of samples: [251, 314]

In [8]:
error_all

[0.9935145406477198,
 0.9949448603396924,
 1.0,
 1.0,
 0.9971148502468531,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [9]:
train_test = format_data_origin(path_train, path_test)

#(df=train_test, path_errors="/home/enrique/Documentos/AutoML_in_data_aumentation/taks/PolitiES/model/results/errors/logistic_error.csv")

ValueError: Invalid file path or buffer object type: <class 'NoneType'>

In [ ]:
train_test